/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace StormThrift
{

  public partial class ErrorInfo : TBase
  {
    private string _host;
    private int _port;

    public string Error { get; set; }

    public int Error_time_secs { get; set; }

    public string Host
    {
      get
      {
        return _host;
      }
      set
      {
        __isset.host = true;
        this._host = value;
      }
    }

    public int Port
    {
      get
      {
        return _port;
      }
      set
      {
        __isset.port = true;
        this._port = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool host;
      public bool port;
    }

    public ErrorInfo()
    {
    }

    public ErrorInfo(string error, int error_time_secs) : this()
    {
      this.Error = error;
      this.Error_time_secs = error_time_secs;
    }

    public ErrorInfo DeepCopy()
    {
      var tmp172 = new ErrorInfo();
      if((Error != null))
      {
        tmp172.Error = this.Error;
      }
      tmp172.Error_time_secs = this.Error_time_secs;
      if((Host != null) && __isset.host)
      {
        tmp172.Host = this.Host;
      }
      tmp172.__isset.host = this.__isset.host;
      if(__isset.port)
      {
        tmp172.Port = this.Port;
      }
      tmp172.__isset.port = this.__isset.port;
      return tmp172;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_error = false;
        bool isset_error_time_secs = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Error = await iprot.ReadStringAsync(cancellationToken);
                isset_error = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                Error_time_secs = await iprot.ReadI32Async(cancellationToken);
                isset_error_time_secs = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.String)
              {
                Host = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.I32)
              {
                Port = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_error)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_error_time_secs)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp173 = new TStruct("ErrorInfo");
        await oprot.WriteStructBeginAsync(tmp173, cancellationToken);
        var tmp174 = new TField();
        if((Error != null))
        {
          tmp174.Name = "error";
          tmp174.Type = TType.String;
          tmp174.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp174, cancellationToken);
          await oprot.WriteStringAsync(Error, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        tmp174.Name = "error_time_secs";
        tmp174.Type = TType.I32;
        tmp174.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp174, cancellationToken);
        await oprot.WriteI32Async(Error_time_secs, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if((Host != null) && __isset.host)
        {
          tmp174.Name = "host";
          tmp174.Type = TType.String;
          tmp174.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp174, cancellationToken);
          await oprot.WriteStringAsync(Host, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.port)
        {
          tmp174.Name = "port";
          tmp174.Type = TType.I32;
          tmp174.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp174, cancellationToken);
          await oprot.WriteI32Async(Port, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is ErrorInfo other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Error, other.Error)
        && global::System.Object.Equals(Error_time_secs, other.Error_time_secs)
        && ((__isset.host == other.__isset.host) && ((!__isset.host) || (global::System.Object.Equals(Host, other.Host))))
        && ((__isset.port == other.__isset.port) && ((!__isset.port) || (global::System.Object.Equals(Port, other.Port))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Error != null))
        {
          hashcode = (hashcode * 397) + Error.GetHashCode();
        }
        hashcode = (hashcode * 397) + Error_time_secs.GetHashCode();
        if((Host != null) && __isset.host)
        {
          hashcode = (hashcode * 397) + Host.GetHashCode();
        }
        if(__isset.port)
        {
          hashcode = (hashcode * 397) + Port.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp175 = new StringBuilder("ErrorInfo(");
      if((Error != null))
      {
        tmp175.Append(", Error: ");
        Error.ToString(tmp175);
      }
      tmp175.Append(", Error_time_secs: ");
      Error_time_secs.ToString(tmp175);
      if((Host != null) && __isset.host)
      {
        tmp175.Append(", Host: ");
        Host.ToString(tmp175);
      }
      if(__isset.port)
      {
        tmp175.Append(", Port: ");
        Port.ToString(tmp175);
      }
      tmp175.Append(')');
      return tmp175.ToString();
    }
  }

}
