/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace StormThrift
{

  public partial class LogConfig : TBase
  {
    private Dictionary<string, global::StormThrift.LogLevel> _named_logger_level;

    public Dictionary<string, global::StormThrift.LogLevel> Named_logger_level
    {
      get
      {
        return _named_logger_level;
      }
      set
      {
        __isset.named_logger_level = true;
        this._named_logger_level = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool named_logger_level;
    }

    public LogConfig()
    {
    }

    public LogConfig DeepCopy()
    {
      var tmp696 = new LogConfig();
      if((Named_logger_level != null) && __isset.named_logger_level)
      {
        tmp696.Named_logger_level = this.Named_logger_level.DeepCopy();
      }
      tmp696.__isset.named_logger_level = this.__isset.named_logger_level;
      return tmp696;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 2:
              if (field.Type == TType.Map)
              {
                {
                  TMap _map697 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Named_logger_level = new Dictionary<string, global::StormThrift.LogLevel>(_map697.Count);
                  for(int _i698 = 0; _i698 < _map697.Count; ++_i698)
                  {
                    string _key699;
                    global::StormThrift.LogLevel _val700;
                    _key699 = await iprot.ReadStringAsync(cancellationToken);
                    _val700 = new global::StormThrift.LogLevel();
                    await _val700.ReadAsync(iprot, cancellationToken);
                    Named_logger_level[_key699] = _val700;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp701 = new TStruct("LogConfig");
        await oprot.WriteStructBeginAsync(tmp701, cancellationToken);
        var tmp702 = new TField();
        if((Named_logger_level != null) && __isset.named_logger_level)
        {
          tmp702.Name = "named_logger_level";
          tmp702.Type = TType.Map;
          tmp702.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp702, cancellationToken);
          {
            await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Named_logger_level.Count), cancellationToken);
            foreach (string _iter703 in Named_logger_level.Keys)
            {
              await oprot.WriteStringAsync(_iter703, cancellationToken);
              await Named_logger_level[_iter703].WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteMapEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is LogConfig other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.named_logger_level == other.__isset.named_logger_level) && ((!__isset.named_logger_level) || (TCollections.Equals(Named_logger_level, other.Named_logger_level))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Named_logger_level != null) && __isset.named_logger_level)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Named_logger_level);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp704 = new StringBuilder("LogConfig(");
      int tmp705 = 0;
      if((Named_logger_level != null) && __isset.named_logger_level)
      {
        if(0 < tmp705++) { tmp704.Append(", "); }
        tmp704.Append("Named_logger_level: ");
        Named_logger_level.ToString(tmp704);
      }
      tmp704.Append(')');
      return tmp704.ToString();
    }
  }

}
