/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace StormThrift
{

  public partial class ThriftSerializedObject : TBase
  {

    public string Name { get; set; }

    public byte[] Bits { get; set; }

    public ThriftSerializedObject()
    {
    }

    public ThriftSerializedObject(string name, byte[] bits) : this()
    {
      this.Name = name;
      this.Bits = bits;
    }

    public ThriftSerializedObject DeepCopy()
    {
      var tmp601 = new ThriftSerializedObject();
      if((Name != null))
      {
        tmp601.Name = this.Name;
      }
      if((Bits != null))
      {
        tmp601.Bits = this.Bits.ToArray();
      }
      return tmp601;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_name = false;
        bool isset_bits = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Name = await iprot.ReadStringAsync(cancellationToken);
                isset_name = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Bits = await iprot.ReadBinaryAsync(cancellationToken);
                isset_bits = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_name)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_bits)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp602 = new TStruct("ThriftSerializedObject");
        await oprot.WriteStructBeginAsync(tmp602, cancellationToken);
        var tmp603 = new TField();
        if((Name != null))
        {
          tmp603.Name = "name";
          tmp603.Type = TType.String;
          tmp603.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp603, cancellationToken);
          await oprot.WriteStringAsync(Name, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Bits != null))
        {
          tmp603.Name = "bits";
          tmp603.Type = TType.String;
          tmp603.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp603, cancellationToken);
          await oprot.WriteBinaryAsync(Bits, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is ThriftSerializedObject other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Name, other.Name)
        && TCollections.Equals(Bits, other.Bits);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Name != null))
        {
          hashcode = (hashcode * 397) + Name.GetHashCode();
        }
        if((Bits != null))
        {
          hashcode = (hashcode * 397) + Bits.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp604 = new StringBuilder("ThriftSerializedObject(");
      if((Name != null))
      {
        tmp604.Append(", Name: ");
        Name.ToString(tmp604);
      }
      if((Bits != null))
      {
        tmp604.Append(", Bits: ");
        Bits.ToString(tmp604);
      }
      tmp604.Append(')');
      return tmp604.ToString();
    }
  }

}
