/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace StormThrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TopologyHistoryInfo : TBase
  {
    private List<string> _topo_ids;

    public List<string> Topo_ids
    {
      get
      {
        return _topo_ids;
      }
      set
      {
        __isset.topo_ids = true;
        this._topo_ids = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool topo_ids;
    }

    public TopologyHistoryInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Topo_ids = new List<string>();
                TList _list357 = iprot.ReadListBegin();
                for( int _i358 = 0; _i358 < _list357.Count; ++_i358)
                {
                  string _elem359 = null;
                  _elem359 = iprot.ReadString();
                  Topo_ids.Add(_elem359);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TopologyHistoryInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Topo_ids != null && __isset.topo_ids) {
        field.Name = "topo_ids";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Topo_ids.Count));
          foreach (string _iter360 in Topo_ids)
          {
            oprot.WriteString(_iter360);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TopologyHistoryInfo(");
      sb.Append("Topo_ids: ");
      sb.Append(Topo_ids);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
