/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace StormThrift
{

  public partial class TopologyPageInfo : TBase
  {
    private string _name;
    private int _uptime_secs;
    private string _status;
    private int _num_tasks;
    private int _num_workers;
    private int _num_executors;
    private string _topology_conf;
    private Dictionary<string, global::StormThrift.ComponentAggregateStats> _id_to_spout_agg_stats;
    private Dictionary<string, global::StormThrift.ComponentAggregateStats> _id_to_bolt_agg_stats;
    private string _sched_status;
    private global::StormThrift.TopologyStats _topology_stats;
    private string _owner;
    private global::StormThrift.DebugOptions _debug_options;
    private int _replication_count;
    private double _requested_memonheap;
    private double _requested_memoffheap;
    private double _requested_cpu;
    private double _assigned_memonheap;
    private double _assigned_memoffheap;
    private double _assigned_cpu;

    public string Id { get; set; }

    public string Name
    {
      get
      {
        return _name;
      }
      set
      {
        __isset.name = true;
        this._name = value;
      }
    }

    public int Uptime_secs
    {
      get
      {
        return _uptime_secs;
      }
      set
      {
        __isset.uptime_secs = true;
        this._uptime_secs = value;
      }
    }

    public string Status
    {
      get
      {
        return _status;
      }
      set
      {
        __isset.status = true;
        this._status = value;
      }
    }

    public int Num_tasks
    {
      get
      {
        return _num_tasks;
      }
      set
      {
        __isset.num_tasks = true;
        this._num_tasks = value;
      }
    }

    public int Num_workers
    {
      get
      {
        return _num_workers;
      }
      set
      {
        __isset.num_workers = true;
        this._num_workers = value;
      }
    }

    public int Num_executors
    {
      get
      {
        return _num_executors;
      }
      set
      {
        __isset.num_executors = true;
        this._num_executors = value;
      }
    }

    public string Topology_conf
    {
      get
      {
        return _topology_conf;
      }
      set
      {
        __isset.topology_conf = true;
        this._topology_conf = value;
      }
    }

    public Dictionary<string, global::StormThrift.ComponentAggregateStats> Id_to_spout_agg_stats
    {
      get
      {
        return _id_to_spout_agg_stats;
      }
      set
      {
        __isset.id_to_spout_agg_stats = true;
        this._id_to_spout_agg_stats = value;
      }
    }

    public Dictionary<string, global::StormThrift.ComponentAggregateStats> Id_to_bolt_agg_stats
    {
      get
      {
        return _id_to_bolt_agg_stats;
      }
      set
      {
        __isset.id_to_bolt_agg_stats = true;
        this._id_to_bolt_agg_stats = value;
      }
    }

    public string Sched_status
    {
      get
      {
        return _sched_status;
      }
      set
      {
        __isset.sched_status = true;
        this._sched_status = value;
      }
    }

    public global::StormThrift.TopologyStats Topology_stats
    {
      get
      {
        return _topology_stats;
      }
      set
      {
        __isset.topology_stats = true;
        this._topology_stats = value;
      }
    }

    public string Owner
    {
      get
      {
        return _owner;
      }
      set
      {
        __isset.owner = true;
        this._owner = value;
      }
    }

    public global::StormThrift.DebugOptions Debug_options
    {
      get
      {
        return _debug_options;
      }
      set
      {
        __isset.debug_options = true;
        this._debug_options = value;
      }
    }

    public int Replication_count
    {
      get
      {
        return _replication_count;
      }
      set
      {
        __isset.replication_count = true;
        this._replication_count = value;
      }
    }

    public double Requested_memonheap
    {
      get
      {
        return _requested_memonheap;
      }
      set
      {
        __isset.requested_memonheap = true;
        this._requested_memonheap = value;
      }
    }

    public double Requested_memoffheap
    {
      get
      {
        return _requested_memoffheap;
      }
      set
      {
        __isset.requested_memoffheap = true;
        this._requested_memoffheap = value;
      }
    }

    public double Requested_cpu
    {
      get
      {
        return _requested_cpu;
      }
      set
      {
        __isset.requested_cpu = true;
        this._requested_cpu = value;
      }
    }

    public double Assigned_memonheap
    {
      get
      {
        return _assigned_memonheap;
      }
      set
      {
        __isset.assigned_memonheap = true;
        this._assigned_memonheap = value;
      }
    }

    public double Assigned_memoffheap
    {
      get
      {
        return _assigned_memoffheap;
      }
      set
      {
        __isset.assigned_memoffheap = true;
        this._assigned_memoffheap = value;
      }
    }

    public double Assigned_cpu
    {
      get
      {
        return _assigned_cpu;
      }
      set
      {
        __isset.assigned_cpu = true;
        this._assigned_cpu = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool name;
      public bool uptime_secs;
      public bool status;
      public bool num_tasks;
      public bool num_workers;
      public bool num_executors;
      public bool topology_conf;
      public bool id_to_spout_agg_stats;
      public bool id_to_bolt_agg_stats;
      public bool sched_status;
      public bool topology_stats;
      public bool owner;
      public bool debug_options;
      public bool replication_count;
      public bool requested_memonheap;
      public bool requested_memoffheap;
      public bool requested_cpu;
      public bool assigned_memonheap;
      public bool assigned_memoffheap;
      public bool assigned_cpu;
    }

    public TopologyPageInfo()
    {
    }

    public TopologyPageInfo(string id) : this()
    {
      this.Id = id;
    }

    public TopologyPageInfo DeepCopy()
    {
      var tmp390 = new TopologyPageInfo();
      if((Id != null))
      {
        tmp390.Id = this.Id;
      }
      if((Name != null) && __isset.name)
      {
        tmp390.Name = this.Name;
      }
      tmp390.__isset.name = this.__isset.name;
      if(__isset.uptime_secs)
      {
        tmp390.Uptime_secs = this.Uptime_secs;
      }
      tmp390.__isset.uptime_secs = this.__isset.uptime_secs;
      if((Status != null) && __isset.status)
      {
        tmp390.Status = this.Status;
      }
      tmp390.__isset.status = this.__isset.status;
      if(__isset.num_tasks)
      {
        tmp390.Num_tasks = this.Num_tasks;
      }
      tmp390.__isset.num_tasks = this.__isset.num_tasks;
      if(__isset.num_workers)
      {
        tmp390.Num_workers = this.Num_workers;
      }
      tmp390.__isset.num_workers = this.__isset.num_workers;
      if(__isset.num_executors)
      {
        tmp390.Num_executors = this.Num_executors;
      }
      tmp390.__isset.num_executors = this.__isset.num_executors;
      if((Topology_conf != null) && __isset.topology_conf)
      {
        tmp390.Topology_conf = this.Topology_conf;
      }
      tmp390.__isset.topology_conf = this.__isset.topology_conf;
      if((Id_to_spout_agg_stats != null) && __isset.id_to_spout_agg_stats)
      {
        tmp390.Id_to_spout_agg_stats = this.Id_to_spout_agg_stats.DeepCopy();
      }
      tmp390.__isset.id_to_spout_agg_stats = this.__isset.id_to_spout_agg_stats;
      if((Id_to_bolt_agg_stats != null) && __isset.id_to_bolt_agg_stats)
      {
        tmp390.Id_to_bolt_agg_stats = this.Id_to_bolt_agg_stats.DeepCopy();
      }
      tmp390.__isset.id_to_bolt_agg_stats = this.__isset.id_to_bolt_agg_stats;
      if((Sched_status != null) && __isset.sched_status)
      {
        tmp390.Sched_status = this.Sched_status;
      }
      tmp390.__isset.sched_status = this.__isset.sched_status;
      if((Topology_stats != null) && __isset.topology_stats)
      {
        tmp390.Topology_stats = (global::StormThrift.TopologyStats)this.Topology_stats.DeepCopy();
      }
      tmp390.__isset.topology_stats = this.__isset.topology_stats;
      if((Owner != null) && __isset.owner)
      {
        tmp390.Owner = this.Owner;
      }
      tmp390.__isset.owner = this.__isset.owner;
      if((Debug_options != null) && __isset.debug_options)
      {
        tmp390.Debug_options = (global::StormThrift.DebugOptions)this.Debug_options.DeepCopy();
      }
      tmp390.__isset.debug_options = this.__isset.debug_options;
      if(__isset.replication_count)
      {
        tmp390.Replication_count = this.Replication_count;
      }
      tmp390.__isset.replication_count = this.__isset.replication_count;
      if(__isset.requested_memonheap)
      {
        tmp390.Requested_memonheap = this.Requested_memonheap;
      }
      tmp390.__isset.requested_memonheap = this.__isset.requested_memonheap;
      if(__isset.requested_memoffheap)
      {
        tmp390.Requested_memoffheap = this.Requested_memoffheap;
      }
      tmp390.__isset.requested_memoffheap = this.__isset.requested_memoffheap;
      if(__isset.requested_cpu)
      {
        tmp390.Requested_cpu = this.Requested_cpu;
      }
      tmp390.__isset.requested_cpu = this.__isset.requested_cpu;
      if(__isset.assigned_memonheap)
      {
        tmp390.Assigned_memonheap = this.Assigned_memonheap;
      }
      tmp390.__isset.assigned_memonheap = this.__isset.assigned_memonheap;
      if(__isset.assigned_memoffheap)
      {
        tmp390.Assigned_memoffheap = this.Assigned_memoffheap;
      }
      tmp390.__isset.assigned_memoffheap = this.__isset.assigned_memoffheap;
      if(__isset.assigned_cpu)
      {
        tmp390.Assigned_cpu = this.Assigned_cpu;
      }
      tmp390.__isset.assigned_cpu = this.__isset.assigned_cpu;
      return tmp390;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_id = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Id = await iprot.ReadStringAsync(cancellationToken);
                isset_id = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Name = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I32)
              {
                Uptime_secs = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.String)
              {
                Status = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.I32)
              {
                Num_tasks = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 6:
              if (field.Type == TType.I32)
              {
                Num_workers = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 7:
              if (field.Type == TType.I32)
              {
                Num_executors = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 8:
              if (field.Type == TType.String)
              {
                Topology_conf = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 9:
              if (field.Type == TType.Map)
              {
                {
                  TMap _map391 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Id_to_spout_agg_stats = new Dictionary<string, global::StormThrift.ComponentAggregateStats>(_map391.Count);
                  for(int _i392 = 0; _i392 < _map391.Count; ++_i392)
                  {
                    string _key393;
                    global::StormThrift.ComponentAggregateStats _val394;
                    _key393 = await iprot.ReadStringAsync(cancellationToken);
                    _val394 = new global::StormThrift.ComponentAggregateStats();
                    await _val394.ReadAsync(iprot, cancellationToken);
                    Id_to_spout_agg_stats[_key393] = _val394;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 10:
              if (field.Type == TType.Map)
              {
                {
                  TMap _map395 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Id_to_bolt_agg_stats = new Dictionary<string, global::StormThrift.ComponentAggregateStats>(_map395.Count);
                  for(int _i396 = 0; _i396 < _map395.Count; ++_i396)
                  {
                    string _key397;
                    global::StormThrift.ComponentAggregateStats _val398;
                    _key397 = await iprot.ReadStringAsync(cancellationToken);
                    _val398 = new global::StormThrift.ComponentAggregateStats();
                    await _val398.ReadAsync(iprot, cancellationToken);
                    Id_to_bolt_agg_stats[_key397] = _val398;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 11:
              if (field.Type == TType.String)
              {
                Sched_status = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 12:
              if (field.Type == TType.Struct)
              {
                Topology_stats = new global::StormThrift.TopologyStats();
                await Topology_stats.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 13:
              if (field.Type == TType.String)
              {
                Owner = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 14:
              if (field.Type == TType.Struct)
              {
                Debug_options = new global::StormThrift.DebugOptions();
                await Debug_options.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 15:
              if (field.Type == TType.I32)
              {
                Replication_count = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 521:
              if (field.Type == TType.Double)
              {
                Requested_memonheap = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 522:
              if (field.Type == TType.Double)
              {
                Requested_memoffheap = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 523:
              if (field.Type == TType.Double)
              {
                Requested_cpu = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 524:
              if (field.Type == TType.Double)
              {
                Assigned_memonheap = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 525:
              if (field.Type == TType.Double)
              {
                Assigned_memoffheap = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 526:
              if (field.Type == TType.Double)
              {
                Assigned_cpu = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_id)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp399 = new TStruct("TopologyPageInfo");
        await oprot.WriteStructBeginAsync(tmp399, cancellationToken);
        var tmp400 = new TField();
        if((Id != null))
        {
          tmp400.Name = "id";
          tmp400.Type = TType.String;
          tmp400.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteStringAsync(Id, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Name != null) && __isset.name)
        {
          tmp400.Name = "name";
          tmp400.Type = TType.String;
          tmp400.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteStringAsync(Name, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.uptime_secs)
        {
          tmp400.Name = "uptime_secs";
          tmp400.Type = TType.I32;
          tmp400.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteI32Async(Uptime_secs, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Status != null) && __isset.status)
        {
          tmp400.Name = "status";
          tmp400.Type = TType.String;
          tmp400.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteStringAsync(Status, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.num_tasks)
        {
          tmp400.Name = "num_tasks";
          tmp400.Type = TType.I32;
          tmp400.ID = 5;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteI32Async(Num_tasks, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.num_workers)
        {
          tmp400.Name = "num_workers";
          tmp400.Type = TType.I32;
          tmp400.ID = 6;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteI32Async(Num_workers, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.num_executors)
        {
          tmp400.Name = "num_executors";
          tmp400.Type = TType.I32;
          tmp400.ID = 7;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteI32Async(Num_executors, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Topology_conf != null) && __isset.topology_conf)
        {
          tmp400.Name = "topology_conf";
          tmp400.Type = TType.String;
          tmp400.ID = 8;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteStringAsync(Topology_conf, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Id_to_spout_agg_stats != null) && __isset.id_to_spout_agg_stats)
        {
          tmp400.Name = "id_to_spout_agg_stats";
          tmp400.Type = TType.Map;
          tmp400.ID = 9;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          {
            await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Id_to_spout_agg_stats.Count), cancellationToken);
            foreach (string _iter401 in Id_to_spout_agg_stats.Keys)
            {
              await oprot.WriteStringAsync(_iter401, cancellationToken);
              await Id_to_spout_agg_stats[_iter401].WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteMapEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Id_to_bolt_agg_stats != null) && __isset.id_to_bolt_agg_stats)
        {
          tmp400.Name = "id_to_bolt_agg_stats";
          tmp400.Type = TType.Map;
          tmp400.ID = 10;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          {
            await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Id_to_bolt_agg_stats.Count), cancellationToken);
            foreach (string _iter402 in Id_to_bolt_agg_stats.Keys)
            {
              await oprot.WriteStringAsync(_iter402, cancellationToken);
              await Id_to_bolt_agg_stats[_iter402].WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteMapEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Sched_status != null) && __isset.sched_status)
        {
          tmp400.Name = "sched_status";
          tmp400.Type = TType.String;
          tmp400.ID = 11;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteStringAsync(Sched_status, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Topology_stats != null) && __isset.topology_stats)
        {
          tmp400.Name = "topology_stats";
          tmp400.Type = TType.Struct;
          tmp400.ID = 12;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await Topology_stats.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Owner != null) && __isset.owner)
        {
          tmp400.Name = "owner";
          tmp400.Type = TType.String;
          tmp400.ID = 13;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteStringAsync(Owner, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Debug_options != null) && __isset.debug_options)
        {
          tmp400.Name = "debug_options";
          tmp400.Type = TType.Struct;
          tmp400.ID = 14;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await Debug_options.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.replication_count)
        {
          tmp400.Name = "replication_count";
          tmp400.Type = TType.I32;
          tmp400.ID = 15;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteI32Async(Replication_count, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.requested_memonheap)
        {
          tmp400.Name = "requested_memonheap";
          tmp400.Type = TType.Double;
          tmp400.ID = 521;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteDoubleAsync(Requested_memonheap, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.requested_memoffheap)
        {
          tmp400.Name = "requested_memoffheap";
          tmp400.Type = TType.Double;
          tmp400.ID = 522;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteDoubleAsync(Requested_memoffheap, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.requested_cpu)
        {
          tmp400.Name = "requested_cpu";
          tmp400.Type = TType.Double;
          tmp400.ID = 523;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteDoubleAsync(Requested_cpu, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.assigned_memonheap)
        {
          tmp400.Name = "assigned_memonheap";
          tmp400.Type = TType.Double;
          tmp400.ID = 524;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteDoubleAsync(Assigned_memonheap, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.assigned_memoffheap)
        {
          tmp400.Name = "assigned_memoffheap";
          tmp400.Type = TType.Double;
          tmp400.ID = 525;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteDoubleAsync(Assigned_memoffheap, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.assigned_cpu)
        {
          tmp400.Name = "assigned_cpu";
          tmp400.Type = TType.Double;
          tmp400.ID = 526;
          await oprot.WriteFieldBeginAsync(tmp400, cancellationToken);
          await oprot.WriteDoubleAsync(Assigned_cpu, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is TopologyPageInfo other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Id, other.Id)
        && ((__isset.name == other.__isset.name) && ((!__isset.name) || (global::System.Object.Equals(Name, other.Name))))
        && ((__isset.uptime_secs == other.__isset.uptime_secs) && ((!__isset.uptime_secs) || (global::System.Object.Equals(Uptime_secs, other.Uptime_secs))))
        && ((__isset.status == other.__isset.status) && ((!__isset.status) || (global::System.Object.Equals(Status, other.Status))))
        && ((__isset.num_tasks == other.__isset.num_tasks) && ((!__isset.num_tasks) || (global::System.Object.Equals(Num_tasks, other.Num_tasks))))
        && ((__isset.num_workers == other.__isset.num_workers) && ((!__isset.num_workers) || (global::System.Object.Equals(Num_workers, other.Num_workers))))
        && ((__isset.num_executors == other.__isset.num_executors) && ((!__isset.num_executors) || (global::System.Object.Equals(Num_executors, other.Num_executors))))
        && ((__isset.topology_conf == other.__isset.topology_conf) && ((!__isset.topology_conf) || (global::System.Object.Equals(Topology_conf, other.Topology_conf))))
        && ((__isset.id_to_spout_agg_stats == other.__isset.id_to_spout_agg_stats) && ((!__isset.id_to_spout_agg_stats) || (TCollections.Equals(Id_to_spout_agg_stats, other.Id_to_spout_agg_stats))))
        && ((__isset.id_to_bolt_agg_stats == other.__isset.id_to_bolt_agg_stats) && ((!__isset.id_to_bolt_agg_stats) || (TCollections.Equals(Id_to_bolt_agg_stats, other.Id_to_bolt_agg_stats))))
        && ((__isset.sched_status == other.__isset.sched_status) && ((!__isset.sched_status) || (global::System.Object.Equals(Sched_status, other.Sched_status))))
        && ((__isset.topology_stats == other.__isset.topology_stats) && ((!__isset.topology_stats) || (global::System.Object.Equals(Topology_stats, other.Topology_stats))))
        && ((__isset.owner == other.__isset.owner) && ((!__isset.owner) || (global::System.Object.Equals(Owner, other.Owner))))
        && ((__isset.debug_options == other.__isset.debug_options) && ((!__isset.debug_options) || (global::System.Object.Equals(Debug_options, other.Debug_options))))
        && ((__isset.replication_count == other.__isset.replication_count) && ((!__isset.replication_count) || (global::System.Object.Equals(Replication_count, other.Replication_count))))
        && ((__isset.requested_memonheap == other.__isset.requested_memonheap) && ((!__isset.requested_memonheap) || (global::System.Object.Equals(Requested_memonheap, other.Requested_memonheap))))
        && ((__isset.requested_memoffheap == other.__isset.requested_memoffheap) && ((!__isset.requested_memoffheap) || (global::System.Object.Equals(Requested_memoffheap, other.Requested_memoffheap))))
        && ((__isset.requested_cpu == other.__isset.requested_cpu) && ((!__isset.requested_cpu) || (global::System.Object.Equals(Requested_cpu, other.Requested_cpu))))
        && ((__isset.assigned_memonheap == other.__isset.assigned_memonheap) && ((!__isset.assigned_memonheap) || (global::System.Object.Equals(Assigned_memonheap, other.Assigned_memonheap))))
        && ((__isset.assigned_memoffheap == other.__isset.assigned_memoffheap) && ((!__isset.assigned_memoffheap) || (global::System.Object.Equals(Assigned_memoffheap, other.Assigned_memoffheap))))
        && ((__isset.assigned_cpu == other.__isset.assigned_cpu) && ((!__isset.assigned_cpu) || (global::System.Object.Equals(Assigned_cpu, other.Assigned_cpu))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Id != null))
        {
          hashcode = (hashcode * 397) + Id.GetHashCode();
        }
        if((Name != null) && __isset.name)
        {
          hashcode = (hashcode * 397) + Name.GetHashCode();
        }
        if(__isset.uptime_secs)
        {
          hashcode = (hashcode * 397) + Uptime_secs.GetHashCode();
        }
        if((Status != null) && __isset.status)
        {
          hashcode = (hashcode * 397) + Status.GetHashCode();
        }
        if(__isset.num_tasks)
        {
          hashcode = (hashcode * 397) + Num_tasks.GetHashCode();
        }
        if(__isset.num_workers)
        {
          hashcode = (hashcode * 397) + Num_workers.GetHashCode();
        }
        if(__isset.num_executors)
        {
          hashcode = (hashcode * 397) + Num_executors.GetHashCode();
        }
        if((Topology_conf != null) && __isset.topology_conf)
        {
          hashcode = (hashcode * 397) + Topology_conf.GetHashCode();
        }
        if((Id_to_spout_agg_stats != null) && __isset.id_to_spout_agg_stats)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Id_to_spout_agg_stats);
        }
        if((Id_to_bolt_agg_stats != null) && __isset.id_to_bolt_agg_stats)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Id_to_bolt_agg_stats);
        }
        if((Sched_status != null) && __isset.sched_status)
        {
          hashcode = (hashcode * 397) + Sched_status.GetHashCode();
        }
        if((Topology_stats != null) && __isset.topology_stats)
        {
          hashcode = (hashcode * 397) + Topology_stats.GetHashCode();
        }
        if((Owner != null) && __isset.owner)
        {
          hashcode = (hashcode * 397) + Owner.GetHashCode();
        }
        if((Debug_options != null) && __isset.debug_options)
        {
          hashcode = (hashcode * 397) + Debug_options.GetHashCode();
        }
        if(__isset.replication_count)
        {
          hashcode = (hashcode * 397) + Replication_count.GetHashCode();
        }
        if(__isset.requested_memonheap)
        {
          hashcode = (hashcode * 397) + Requested_memonheap.GetHashCode();
        }
        if(__isset.requested_memoffheap)
        {
          hashcode = (hashcode * 397) + Requested_memoffheap.GetHashCode();
        }
        if(__isset.requested_cpu)
        {
          hashcode = (hashcode * 397) + Requested_cpu.GetHashCode();
        }
        if(__isset.assigned_memonheap)
        {
          hashcode = (hashcode * 397) + Assigned_memonheap.GetHashCode();
        }
        if(__isset.assigned_memoffheap)
        {
          hashcode = (hashcode * 397) + Assigned_memoffheap.GetHashCode();
        }
        if(__isset.assigned_cpu)
        {
          hashcode = (hashcode * 397) + Assigned_cpu.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp403 = new StringBuilder("TopologyPageInfo(");
      if((Id != null))
      {
        tmp403.Append(", Id: ");
        Id.ToString(tmp403);
      }
      if((Name != null) && __isset.name)
      {
        tmp403.Append(", Name: ");
        Name.ToString(tmp403);
      }
      if(__isset.uptime_secs)
      {
        tmp403.Append(", Uptime_secs: ");
        Uptime_secs.ToString(tmp403);
      }
      if((Status != null) && __isset.status)
      {
        tmp403.Append(", Status: ");
        Status.ToString(tmp403);
      }
      if(__isset.num_tasks)
      {
        tmp403.Append(", Num_tasks: ");
        Num_tasks.ToString(tmp403);
      }
      if(__isset.num_workers)
      {
        tmp403.Append(", Num_workers: ");
        Num_workers.ToString(tmp403);
      }
      if(__isset.num_executors)
      {
        tmp403.Append(", Num_executors: ");
        Num_executors.ToString(tmp403);
      }
      if((Topology_conf != null) && __isset.topology_conf)
      {
        tmp403.Append(", Topology_conf: ");
        Topology_conf.ToString(tmp403);
      }
      if((Id_to_spout_agg_stats != null) && __isset.id_to_spout_agg_stats)
      {
        tmp403.Append(", Id_to_spout_agg_stats: ");
        Id_to_spout_agg_stats.ToString(tmp403);
      }
      if((Id_to_bolt_agg_stats != null) && __isset.id_to_bolt_agg_stats)
      {
        tmp403.Append(", Id_to_bolt_agg_stats: ");
        Id_to_bolt_agg_stats.ToString(tmp403);
      }
      if((Sched_status != null) && __isset.sched_status)
      {
        tmp403.Append(", Sched_status: ");
        Sched_status.ToString(tmp403);
      }
      if((Topology_stats != null) && __isset.topology_stats)
      {
        tmp403.Append(", Topology_stats: ");
        Topology_stats.ToString(tmp403);
      }
      if((Owner != null) && __isset.owner)
      {
        tmp403.Append(", Owner: ");
        Owner.ToString(tmp403);
      }
      if((Debug_options != null) && __isset.debug_options)
      {
        tmp403.Append(", Debug_options: ");
        Debug_options.ToString(tmp403);
      }
      if(__isset.replication_count)
      {
        tmp403.Append(", Replication_count: ");
        Replication_count.ToString(tmp403);
      }
      if(__isset.requested_memonheap)
      {
        tmp403.Append(", Requested_memonheap: ");
        Requested_memonheap.ToString(tmp403);
      }
      if(__isset.requested_memoffheap)
      {
        tmp403.Append(", Requested_memoffheap: ");
        Requested_memoffheap.ToString(tmp403);
      }
      if(__isset.requested_cpu)
      {
        tmp403.Append(", Requested_cpu: ");
        Requested_cpu.ToString(tmp403);
      }
      if(__isset.assigned_memonheap)
      {
        tmp403.Append(", Assigned_memonheap: ");
        Assigned_memonheap.ToString(tmp403);
      }
      if(__isset.assigned_memoffheap)
      {
        tmp403.Append(", Assigned_memoffheap: ");
        Assigned_memoffheap.ToString(tmp403);
      }
      if(__isset.assigned_cpu)
      {
        tmp403.Append(", Assigned_cpu: ");
        Assigned_cpu.ToString(tmp403);
      }
      tmp403.Append(')');
      return tmp403.ToString();
    }
  }

}
