/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Prolucid.ThriftShell.Messages
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Context : TBase
  {

    public int TaskId { get; set; }

    public Dictionary<int, string> TaskComponents { get; set; }

    public string ComponentId { get; set; }

    public Context() {
    }

    public Context(int taskId, Dictionary<int, string> taskComponents, string componentId) : this() {
      this.TaskId = taskId;
      this.TaskComponents = taskComponents;
      this.ComponentId = componentId;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_taskId = false;
      bool isset_taskComponents = false;
      bool isset_componentId = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              TaskId = iprot.ReadI32();
              isset_taskId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                TaskComponents = new Dictionary<int, string>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  string _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = iprot.ReadString();
                  TaskComponents[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
              isset_taskComponents = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              ComponentId = iprot.ReadString();
              isset_componentId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_taskId)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_taskComponents)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_componentId)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Context");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "taskId";
      field.Type = TType.I32;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(TaskId);
      oprot.WriteFieldEnd();
      field.Name = "taskComponents";
      field.Type = TType.Map;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.I32, TType.String, TaskComponents.Count));
        foreach (int _iter4 in TaskComponents.Keys)
        {
          oprot.WriteI32(_iter4);
          oprot.WriteString(TaskComponents[_iter4]);
        }
        oprot.WriteMapEnd();
      }
      oprot.WriteFieldEnd();
      field.Name = "componentId";
      field.Type = TType.String;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(ComponentId);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Context(");
      sb.Append("TaskId: ");
      sb.Append(TaskId);
      sb.Append(",TaskComponents: ");
      sb.Append(TaskComponents);
      sb.Append(",ComponentId: ");
      sb.Append(ComponentId);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
