/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Prolucid.ThriftShell.Messages
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class LogCommand : TBase
  {

    public string Message { get; set; }

    /// <summary>
    /// 
    /// <seealso cref="LogLevel"/>
    /// </summary>
    public LogLevel Level { get; set; }

    public LogCommand() {
    }

    public LogCommand(string message, LogLevel level) : this() {
      this.Message = message;
      this.Level = level;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_message = false;
      bool isset_level = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Message = iprot.ReadString();
              isset_message = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Level = (LogLevel)iprot.ReadI32();
              isset_level = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_message)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_level)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LogCommand");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "message";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Message);
      oprot.WriteFieldEnd();
      field.Name = "level";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)Level);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LogCommand(");
      sb.Append("Message: ");
      sb.Append(Message);
      sb.Append(",Level: ");
      sb.Append(Level);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
