/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Prolucid.ThriftShell.Messages
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TaskIdsReply : TBase
  {

    public List<int> TaskIds { get; set; }

    public TaskIdsReply() {
    }

    public TaskIdsReply(List<int> taskIds) : this() {
      this.TaskIds = taskIds;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_taskIds = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                TaskIds = new List<int>();
                TList _list14 = iprot.ReadListBegin();
                for( int _i15 = 0; _i15 < _list14.Count; ++_i15)
                {
                  int _elem16 = 0;
                  _elem16 = iprot.ReadI32();
                  TaskIds.Add(_elem16);
                }
                iprot.ReadListEnd();
              }
              isset_taskIds = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_taskIds)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TaskIdsReply");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "taskIds";
      field.Type = TType.List;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.I32, TaskIds.Count));
        foreach (int _iter17 in TaskIds)
        {
          oprot.WriteI32(_iter17);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TaskIdsReply(");
      sb.Append("TaskIds: ");
      sb.Append(TaskIds);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
