// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("StormThrift")]
[assembly: AssemblyProductAttribute("FsShelter")]
[assembly: AssemblyDescriptionAttribute("F# DSL and runtime for Storm topologies")]
[assembly: AssemblyVersionAttribute("0.2.5")]
[assembly: AssemblyFileVersionAttribute("0.2.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "StormThrift";
        internal const System.String AssemblyProduct = "FsShelter";
        internal const System.String AssemblyDescription = "F# DSL and runtime for Storm topologies";
        internal const System.String AssemblyVersion = "0.2.5";
        internal const System.String AssemblyFileVersion = "0.2.5";
    }
}
