// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("StormThrift")]
[assembly: AssemblyProductAttribute("FsShelter")]
[assembly: AssemblyDescriptionAttribute("F# DSL and runtime for Storm topologies")]
[assembly: AssemblyVersionAttribute("0.0.5")]
[assembly: AssemblyFileVersionAttribute("0.0.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.5";
    }
}
