/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace StormThrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Credentials : TBase
  {

    public Dictionary<string, string> Creds { get; set; }

    public Credentials() {
    }

    public Credentials(Dictionary<string, string> creds) : this() {
      this.Creds = creds;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_creds = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                Creds = new Dictionary<string, string>();
                TMap _map239 = iprot.ReadMapBegin();
                for( int _i240 = 0; _i240 < _map239.Count; ++_i240)
                {
                  string _key241;
                  string _val242;
                  _key241 = iprot.ReadString();
                  _val242 = iprot.ReadString();
                  Creds[_key241] = _val242;
                }
                iprot.ReadMapEnd();
              }
              isset_creds = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_creds)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Credentials");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "creds";
      field.Type = TType.Map;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.String, TType.String, Creds.Count));
        foreach (string _iter243 in Creds.Keys)
        {
          oprot.WriteString(_iter243);
          oprot.WriteString(Creds[_iter243]);
        }
        oprot.WriteMapEnd();
      }
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Credentials(");
      sb.Append("Creds: ");
      sb.Append(Creds);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
